version: "3.7"

services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - rvolume:/redis/data

  server_pub:
    build: ./publisher-server
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
    ports:
      - "5001:5001"
    depends_on:
      - redis

  server_sub:
    build: ./subscriber-server
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
    ports:
      - "5002:5002"
    depends_on:
      - redis

volumes:
  rvolume:
